name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint-and-typecheck:
    name: Ruff & Mypy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install uv
        uses: astral-sh/setup-uv@v2
        with:
          enable-cache: true
          cache-dependency-glob: "pyproject.toml"

      - name: Install dependencies
        run: |
          uv venv
          uv sync
          uv add ruff mypy types-PyYAML

      - name: Run Ruff Linter
        run: uv run ruff check .

      - name: Run Ruff Formatter
        run: uv run ruff format --check .